---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 4

provisioner:
  name: chef_solo

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.8.1

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

driver_config:
  requre_chef_omnibus: true
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 443, host: 443}]

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/smoke/default
    run_list:
      - recipe[deployment::install]
    attributes:
      test_env: true
