database:
  db_name: test_results_db
  user: root
  password: "0000"

report_portal:
  url: http://localhost:8080
  project_name: testresults_2
  auth_token: "8ee428b5-dcc5-4fba-8e4f-462863dbba15" # Get it from http://localhost:8080/ui/?#user-profile
